### ISSUE TITLE
Replace where to find_by methods for ORM broke Mongoid

### ISSUE THREAD

**Issue by badlamer** [doorkeeper-gem/doorkeeper#900]
Hello. After replace where methods to find_by  in models mixins, broke mongoid compatible.

Method find_by (without bang(!) ) raise Mongoid::Errors::DocumentNotFound.

Broken in #825

**Comment by nbulaj** [comment]
Hi. What version of Mongoid is used? 

How about:

```yaml
development:
  options: 
    raise_not_found_error: false
```

That is the problem a talked before - all those ORM-specific methods must be replaced with some Doorkeeper internal API that can be implemented with different libs (Sequel, Mongoid, etc).
